# Generated by Django 4.1.7 on 2023-05-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_departments_employees_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
