# Generated by Django 4.1.7 on 2023-05-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='Faculty',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='departments',
            name='Hod_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
