# Generated by Django 4.2.1 on 2023-05-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='FacultyAndHOD',
            field=models.JSONField(default=dict),
        ),
    ]
