# Generated by Django 4.2.1 on 2023-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_departments_facultyandhod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='FacultyAndHOD',
        ),
        migrations.AddField(
            model_name='departments',
            name='FacultyAndHod',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
