# Generated by Django 4.2.1 on 2023-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_departments_facultyandhod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='FacultyAndHod',
        ),
        migrations.AddField(
            model_name='departments',
            name='FacultyAndHOD',
            field=models.JSONField(default=dict),
        ),
    ]
