# Generated by Django 4.2.1 on 2023-05-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_departments_facultyandhod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='FacultyAndHOD',
        ),
    ]
